"""Tests for JSON schema utilities."""

import pytest
from pydantic import BaseModel

from lfx.schema.json_schema import create_input_schema_from_json_schema


def test_empty_object_returns_dict():
    """Test that an object with no properties returns dict type."""
    schema = {
        "type": "object",
        "properties": {
            "data": {"type": "object"},
        },
        "required": ["data"],
    }

    model = create_input_schema_from_json_schema(schema)
    assert model.model_fields["data"].annotation == dict


def test_array_of_empty_objects_returns_list_dict():
    """Test that array of objects with no properties returns list[dict].

    This is the schema pattern generated by FastMCP for list[dict] parameters.
    """
    schema = {
        "type": "object",
        "properties": {
            "tables_list": {
                "type": "array",
                "items": {"type": "object"},
            },
        },
        "required": ["tables_list"],
    }

    model = create_input_schema_from_json_schema(schema)
    # Should be list[dict], not list[AnonModel]
    assert model.model_fields["tables_list"].annotation == list[dict]


def test_object_with_properties_returns_model():
    """Test that objects with defined properties create a Pydantic model."""
    schema = {
        "type": "object",
        "properties": {
            "config": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "value": {"type": "integer"},
                },
                "required": ["name"],
            },
        },
        "required": ["config"],
    }

    model = create_input_schema_from_json_schema(schema)
    config_type = model.model_fields["config"].annotation

    # Should be a Pydantic model, not dict
    assert isinstance(config_type, type)
    assert issubclass(config_type, BaseModel)
    assert "name" in config_type.model_fields
    assert "value" in config_type.model_fields


def test_mcp_tool_schema_with_list_dict():
    """Test a real MCP tool schema pattern with tables_list: list[dict].

    This matches the get_sql tool from agents-python DataverseClient.
    """
    schema = {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "Natural language query to generate SQL for",
            },
            "tables_list": {
                "type": "array",
                "items": {"type": "object"},
                "description": "List of table schemas with name, description, and columns",
            },
        },
        "required": ["query", "tables_list"],
    }

    model = create_input_schema_from_json_schema(schema)

    # Verify query is str
    assert model.model_fields["query"].annotation == str

    # Verify tables_list is list[dict]
    assert model.model_fields["tables_list"].annotation == list[dict]

    # Verify we can instantiate the model
    instance = model(
        query="SELECT all users",
        tables_list=[
            {"name": "users", "columns": ["id", "name"]},
            {"name": "orders", "columns": ["id", "user_id"]},
        ],
    )
    assert instance.query == "SELECT all users"
    assert len(instance.tables_list) == 2
    assert instance.tables_list[0]["name"] == "users"


def test_nested_array_of_objects_with_properties():
    """Test array of objects that have defined properties."""
    schema = {
        "type": "object",
        "properties": {
            "items": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "integer"},
                        "name": {"type": "string"},
                    },
                    "required": ["id"],
                },
            },
        },
        "required": ["items"],
    }

    model = create_input_schema_from_json_schema(schema)
    items_annotation = model.model_fields["items"].annotation

    # Get the inner type from list[X]
    inner_type = items_annotation.__args__[0]

    # Should be a Pydantic model since properties are defined
    assert isinstance(inner_type, type)
    assert issubclass(inner_type, BaseModel)
    assert "id" in inner_type.model_fields
    assert "name" in inner_type.model_fields
